// lib/features/bible/core/constants/bible_constants.dart
// Source unique de vérité pour les constantes Bible
// Évite la duplication entre bible_repository_impl.dart et bible_download_service.dart

/// Nombre de chapitres par livre de la Bible (Ancien + Nouveau Testament)
const Map<String, int> bibleChapterCounts = {
  'GEN': 50,
  'EXO': 40,
  'LEV': 27,
  'NUM': 36,
  'DEU': 34,
  'JOS': 24,
  'JDG': 21,
  'RUT': 4,
  '1SA': 31,
  '2SA': 24,
  '1KI': 22,
  '2KI': 25,
  '1CH': 29,
  '2CH': 36,
  'EZR': 10,
  'NEH': 13,
  'EST': 10,
  'JOB': 42,
  'PSA': 150,
  'PRO': 31,
  'ECC': 12,
  'SNG': 8,
  'ISA': 66,
  'JER': 52,
  'LAM': 5,
  'EZK': 48,
  'DAN': 12,
  'HOS': 14,
  'JOL': 3,
  'AMO': 9,
  'OBA': 1,
  'JON': 4,
  'MIC': 7,
  'NAM': 3,
  'HAB': 3,
  'ZEP': 3,
  'HAG': 2,
  'ZEC': 14,
  'MAL': 4,
  'MAT': 28,
  'MRK': 16,
  'LUK': 24,
  'JHN': 21,
  'ACT': 28,
  'ROM': 16,
  '1CO': 16,
  '2CO': 13,
  'GAL': 6,
  'EPH': 6,
  'PHP': 4,
  'COL': 4,
  '1TH': 5,
  '2TH': 3,
  '1TI': 6,
  '2TI': 4,
  'TIT': 3,
  'PHM': 1,
  'HEB': 13,
  'JAS': 5,
  '1PE': 5,
  '2PE': 3,
  '1JN': 5,
  '2JN': 1,
  '3JN': 1,
  'JUD': 1,
  'REV': 22,
};

/// Total number of chapters in the Bible (1189)
int get totalChapterCount =>
    bibleChapterCounts.values.fold(0, (a, b) => a + b);

/// Liste canonique des livres de la Bible
const List<Map<String, String>> canonBibleBooks = [
  {'id': 'GEN', 'name': 'Genèse', 't': 'old'},
  {'id': 'EXO', 'name': 'Exode', 't': 'old'},
  {'id': 'LEV', 'name': 'Lévitique', 't': 'old'},
  {'id': 'NUM', 'name': 'Nombres', 't': 'old'},
  {'id': 'DEU', 'name': 'Deutéronome', 't': 'old'},
  {'id': 'JOS', 'name': 'Josué', 't': 'old'},
  {'id': 'JDG', 'name': 'Juges', 't': 'old'},
  {'id': 'RUT', 'name': 'Ruth', 't': 'old'},
  {'id': '1SA', 'name': '1 Samuel', 't': 'old'},
  {'id': '2SA', 'name': '2 Samuel', 't': 'old'},
  {'id': '1KI', 'name': '1 Rois', 't': 'old'},
  {'id': '2KI', 'name': '2 Rois', 't': 'old'},
  {'id': '1CH', 'name': '1 Chroniques', 't': 'old'},
  {'id': '2CH', 'name': '2 Chroniques', 't': 'old'},
  {'id': 'EZR', 'name': 'Esdras', 't': 'old'},
  {'id': 'NEH', 'name': 'Néhémie', 't': 'old'},
  {'id': 'EST', 'name': 'Esther', 't': 'old'},
  {'id': 'JOB', 'name': 'Job', 't': 'old'},
  {'id': 'PSA', 'name': 'Psaumes', 't': 'old'},
  {'id': 'PRO', 'name': 'Proverbes', 't': 'old'},
  {'id': 'ECC', 'name': 'Ecclésiaste', 't': 'old'},
  {'id': 'SNG', 'name': 'Cantique des Cantiques', 't': 'old'},
  {'id': 'ISA', 'name': 'Ésaïe', 't': 'old'},
  {'id': 'JER', 'name': 'Jérémie', 't': 'old'},
  {'id': 'LAM', 'name': 'Lamentations', 't': 'old'},
  {'id': 'EZK', 'name': 'Ézéchiel', 't': 'old'},
  {'id': 'DAN', 'name': 'Daniel', 't': 'old'},
  {'id': 'HOS', 'name': 'Osée', 't': 'old'},
  {'id': 'JOL', 'name': 'Joël', 't': 'old'},
  {'id': 'AMO', 'name': 'Amos', 't': 'old'},
  {'id': 'OBA', 'name': 'Abdias', 't': 'old'},
  {'id': 'JON', 'name': 'Jonas', 't': 'old'},
  {'id': 'MIC', 'name': 'Michée', 't': 'old'},
  {'id': 'NAM', 'name': 'Nahum', 't': 'old'},
  {'id': 'HAB', 'name': 'Habacuc', 't': 'old'},
  {'id': 'ZEP', 'name': 'Sophonie', 't': 'old'},
  {'id': 'HAG', 'name': 'Aggée', 't': 'old'},
  {'id': 'ZEC', 'name': 'Zacharie', 't': 'old'},
  {'id': 'MAL', 'name': 'Malachie', 't': 'old'},
  {'id': 'MAT', 'name': 'Matthieu', 't': 'new'},
  {'id': 'MRK', 'name': 'Marc', 't': 'new'},
  {'id': 'LUK', 'name': 'Luc', 't': 'new'},
  {'id': 'JHN', 'name': 'Jean', 't': 'new'},
  {'id': 'ACT', 'name': 'Actes', 't': 'new'},
  {'id': 'ROM', 'name': 'Romains', 't': 'new'},
  {'id': '1CO', 'name': '1 Corinthiens', 't': 'new'},
  {'id': '2CO', 'name': '2 Corinthiens', 't': 'new'},
  {'id': 'GAL', 'name': 'Galates', 't': 'new'},
  {'id': 'EPH', 'name': 'Éphésiens', 't': 'new'},
  {'id': 'PHP', 'name': 'Philippiens', 't': 'new'},
  {'id': 'COL', 'name': 'Colossiens', 't': 'new'},
  {'id': '1TH', 'name': '1 Thessaloniciens', 't': 'new'},
  {'id': '2TH', 'name': '2 Thessaloniciens', 't': 'new'},
  {'id': '1TI', 'name': '1 Timothée', 't': 'new'},
  {'id': '2TI', 'name': '2 Timothée', 't': 'new'},
  {'id': 'TIT', 'name': 'Tite', 't': 'new'},
  {'id': 'PHM', 'name': 'Philémon', 't': 'new'},
  {'id': 'HEB', 'name': 'Hébreux', 't': 'new'},
  {'id': 'JAS', 'name': 'Jacques', 't': 'new'},
  {'id': '1PE', 'name': '1 Pierre', 't': 'new'},
  {'id': '2PE', 'name': '2 Pierre', 't': 'new'},
  {'id': '1JN', 'name': '1 Jean', 't': 'new'},
  {'id': '2JN', 'name': '2 Jean', 't': 'new'},
  {'id': '3JN', 'name': '3 Jean', 't': 'new'},
  {'id': 'JUD', 'name': 'Jude', 't': 'new'},
  {'id': 'REV', 'name': 'Apocalypse', 't': 'new'},
];
