// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'church_role.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ChurchRoleImpl _$$ChurchRoleImplFromJson(Map<String, dynamic> json) =>
    _$ChurchRoleImpl(
      id: json['id'] as String,
      churchId: json['church_id'] as String,
      level: $enumDecode(_$RoleLevelEnumMap, json['level']),
      name: json['name'] as String,
      description: json['description'] as String?,
      permissions: (json['permissions'] as List<dynamic>)
          .map((e) => $enumDecode(_$PermissionEnumMap, e))
          .toSet(),
      isActive: json['is_active'] as bool? ?? true,
      isSystemRole: json['is_system_role'] as bool? ?? false,
      createdAt: DateTime.parse(json['created_at'] as String),
      initialRoute: json['initial_route'] as String,
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
    );

Map<String, dynamic> _$$ChurchRoleImplToJson(_$ChurchRoleImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'church_id': instance.churchId,
      'level': _$RoleLevelEnumMap[instance.level]!,
      'name': instance.name,
      'description': instance.description,
      'permissions':
          instance.permissions.map((e) => _$PermissionEnumMap[e]!).toList(),
      'is_active': instance.isActive,
      'is_system_role': instance.isSystemRole,
      'created_at': instance.createdAt.toIso8601String(),
      'initial_route': instance.initialRoute,
      'updated_at': instance.updatedAt?.toIso8601String(),
    };

const _$RoleLevelEnumMap = {
  RoleLevel.adminTotal: 'adminTotal',
  RoleLevel.admin: 'admin',
  RoleLevel.finance: 'finance',
  RoleLevel.staff: 'staff',
  RoleLevel.groupLeader: 'groupLeader',
  RoleLevel.superadmin: 'superadmin',
  RoleLevel.consultation: 'consultation',
  RoleLevel.membre: 'membre',
  RoleLevel.custom: 'custom',
};

const _$PermissionEnumMap = {
  Permission.dashboardView: 'dashboardView',
  Permission.dashboardAdvancedStats: 'dashboardAdvancedStats',
  Permission.membersView: 'membersView',
  Permission.membersCreate: 'membersCreate',
  Permission.membersEdit: 'membersEdit',
  Permission.membersDelete: 'membersDelete',
  Permission.membersExport: 'membersExport',
  Permission.membersSensitiveData: 'membersSensitiveData',
  Permission.financeView: 'financeView',
  Permission.financeCreate: 'financeCreate',
  Permission.financeEdit: 'financeEdit',
  Permission.financeDelete: 'financeDelete',
  Permission.financeApprove: 'financeApprove',
  Permission.financeExport: 'financeExport',
  Permission.financeReports: 'financeReports',
  Permission.financeBalanceView: 'financeBalanceView',
  Permission.financeViewBalance: 'financeViewBalance',
  Permission.eventsView: 'eventsView',
  Permission.eventsCreate: 'eventsCreate',
  Permission.eventsEdit: 'eventsEdit',
  Permission.eventsDelete: 'eventsDelete',
  Permission.eventsManageRegistrations: 'eventsManageRegistrations',
  Permission.eventsReports: 'eventsReports',
  Permission.groupsView: 'groupsView',
  Permission.groupsCreate: 'groupsCreate',
  Permission.groupsEdit: 'groupsEdit',
  Permission.groupsDelete: 'groupsDelete',
  Permission.groupsAssignMembers: 'groupsAssignMembers',
  Permission.celebrationsView: 'celebrationsView',
  Permission.celebrationsCreate: 'celebrationsCreate',
  Permission.celebrationsEdit: 'celebrationsEdit',
  Permission.celebrationsDelete: 'celebrationsDelete',
  Permission.bergersView: 'bergersView',
  Permission.bergersCreate: 'bergersCreate',
  Permission.bergersEdit: 'bergersEdit',
  Permission.bergersDelete: 'bergersDelete',
  Permission.bergersAssignMembers: 'bergersAssignMembers',
  Permission.milestonesView: 'milestonesView',
  Permission.milestonesCreate: 'milestonesCreate',
  Permission.milestonesEdit: 'milestonesEdit',
  Permission.milestonesDelete: 'milestonesDelete',
  Permission.socialView: 'socialView',
  Permission.socialCreate: 'socialCreate',
  Permission.socialEdit: 'socialEdit',
  Permission.socialModerate: 'socialModerate',
  Permission.messagingView: 'messagingView',
  Permission.messagingSend: 'messagingSend',
  Permission.messagingBroadcast: 'messagingBroadcast',
  Permission.communicationsView: 'communicationsView',
  Permission.communicationsCreate: 'communicationsCreate',
  Permission.categoriesView: 'categoriesView',
  Permission.categoriesCreate: 'categoriesCreate',
  Permission.categoriesEdit: 'categoriesEdit',
  Permission.categoriesDelete: 'categoriesDelete',
  Permission.categoriesManageHierarchy: 'categoriesManageHierarchy',
  Permission.accountsView: 'accountsView',
  Permission.accountsCreate: 'accountsCreate',
  Permission.accountsEdit: 'accountsEdit',
  Permission.accountsDelete: 'accountsDelete',
  Permission.accountsTransfer: 'accountsTransfer',
  Permission.budgetView: 'budgetView',
  Permission.budgetCreate: 'budgetCreate',
  Permission.budgetEdit: 'budgetEdit',
  Permission.budgetDelete: 'budgetDelete',
  Permission.adminManageRoles: 'adminManageRoles',
  Permission.adminManageUsers: 'adminManageUsers',
  Permission.adminManageChurches: 'adminManageChurches',
  Permission.adminViewLogs: 'adminViewLogs',
  Permission.adminSettings: 'adminSettings',
  Permission.adminSystemSettings: 'adminSystemSettings',
  Permission.documentsRead: 'documentsRead',
  Permission.documentsWrite: 'documentsWrite',
  Permission.reportsExport: 'reportsExport',
  Permission.reportsView: 'reportsView',
  Permission.auditView: 'auditView',
  Permission.viewDashboard: 'viewDashboard',
  Permission.viewMembres: 'viewMembres',
  Permission.createMembre: 'createMembre',
  Permission.editMembre: 'editMembre',
  Permission.deleteMembre: 'deleteMembre',
  Permission.exportMembres: 'exportMembres',
  Permission.viewFinance: 'viewFinance',
  Permission.createTransaction: 'createTransaction',
  Permission.editTransaction: 'editTransaction',
  Permission.deleteTransaction: 'deleteTransaction',
  Permission.validateTransaction: 'validateTransaction',
  Permission.exportFinance: 'exportFinance',
  Permission.viewEvents: 'viewEvents',
  Permission.createEvent: 'createEvent',
  Permission.editEvent: 'editEvent',
  Permission.deleteEvent: 'deleteEvent',
  Permission.viewGroups: 'viewGroups',
  Permission.createGroup: 'createGroup',
  Permission.editGroup: 'editGroup',
  Permission.deleteGroup: 'deleteGroup',
  Permission.viewCelebrations: 'viewCelebrations',
  Permission.createCelebration: 'createCelebration',
  Permission.editCelebration: 'editCelebration',
  Permission.deleteCelebration: 'deleteCelebration',
  Permission.manageUsers: 'manageUsers',
  Permission.manageRoles: 'manageRoles',
  Permission.manageChurches: 'manageChurches',
  Permission.viewLogs: 'viewLogs',
  Permission.manageSettings: 'manageSettings',
};
